### ISSUE TITLE
error !!can someone help me?

### ISSUE THREAD

**Issue by DarkyUzzy** [Procurement-PoE/Procurement#1146] opened 2022-12-11 08:57 UTC
Procurement 1.29.1 Initialized.
                                                          
Authenticating DarkyUzzy                                                                  [OK]
Fetching account name...                                                                  

[Er
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/10201764/DebugInfo.log)
ror] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by chrlsfrmg** [comment] 2022-12-22 05:37
managed to solve?

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by DarkyUzzy** [comment] 2022-12-22 17:32
> managed to solve?

no.
i tried the new one but still down...

**Comment by Omga4000** [comment] 2022-12-22 18:05
@DarkyUzzy 
In order for this fix to work, your account must be recognized by Poe Watch.
To check if your account is recognized, please use the following tool:
https://poe.watch/Account

**Comment by Omga4000** [comment] 2022-12-22 20:14
@DarkyUzzy 

Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment] 2022-12-22 21:52
Duplicate of #1140.

**Closed by thailyn** 2022-12-22 21:52 UTC
