### ISSUE TITLE
Error downloading acc name

### ISSUE THREAD

**Issue by DarkyUzzy** [Procurement-PoE/Procurement#1141] opened 2022-07-09 06:31 UTC
hello
i get this error while i want to login.
att my debug
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9075985/DebugInfo.log)

**Comment by hydroxiq** [comment] 2022-08-02 21:57
same issue here, debug included 
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9245940/DebugInfo.log)

**Comment by GunsnrosesHG** [comment] 2022-08-26 03:59
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9429695/DebugInfo.log)

**Comment by GunsnrosesHG** [comment] 2022-08-26 04:00
did anyone find a solution ?

**Comment by Omga4000** [comment] 2022-09-14 20:46
Duplicate: #1140

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by DarkyUzzy** [comment] 2022-12-22 17:29
> I've cloned this repository and (temporarily) fixed the issue. Feel free to download the new version I've created from my own repository, it should be public.
> 
> https://github.com/Omga4000/Procurement/releases/tag/1.30.0
> 
> Let me know if that works for you.

Not Working....


[22-12-2022 19:28] Failed to build HTTP request and get response for: method=GET, url='https://api.poe.watch/account?name=DarkyUzzy&realm=pc', allowAutoRedirects=, requestData='': The remote server returned an error: (400) Bad Request.
[22-12-2022 19:28] Error downloading account name, exception details: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   at POEApi.Transport.HttpTransport.GetAccountName(String username, String realm)
   at POEApi.Model.POEModel.GetAccountName(String username, String realm)
[22-12-2022 19:28] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName(String username, String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by DarkyUzzy** [comment] 2022-12-22 17:33
[Omga4000](https://github.com/Omga4000)  ty for trying....
[thailyn](https://github.com/thailyn) don't even bother to respond:)

**Comment by Omga4000** [comment] 2022-12-22 20:13
@DarkyUzzy 

Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment] 2022-12-22 21:48
Duplicate of #1140.

**Closed by thailyn** 2022-12-22 21:48 UTC

**Comment by GunsnrosesHG** [comment] 2023-01-06 18:36
Hey mate, all works fine thank you for your help.
i wanted to get my url by messaging  poexyzis
<https://www.pathofexile.com/account/view-profile/poexyzis> but no respond
