### ISSUE TITLE
[Error] Error downloading account name

### ISSUE THREAD

**Issue by chrlsfrmg** [Procurement-PoE/Procurement#1148] opened 2022-12-22 05:55 UTC
Hi

[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/10284139/DebugInfo.log)

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by chrlsfrmg** [comment] 2022-12-22 09:03
![image](https://user-images.githubusercontent.com/67290803/209097867-f64b3807-ffd4-4c7c-9589-d853ad467e8a.png)

**Comment by Omga4000** [comment] 2022-12-22 09:07
@chrlsfrmg 
Your account name was not found.
Verified manually - it really wasn't found.

When was the last time you've logged into the game?
If it was before 11.08.2020, you will not be able to use it.
You can use this tool to check whether the API can find your account or not: https://poe.watch/Account

**Comment by chrlsfrmg** [comment] 2022-12-22 09:08
![image](https://user-images.githubusercontent.com/67290803/209098790-e165d5b8-9b55-45f3-8e42-8802cad689dd.png)
?

**Comment by chrlsfrmg** [comment] 2022-12-22 09:09
> @chrlsfrmg O nome da sua conta não foi encontrado. Verificado manualmente - realmente não foi encontrado.
> 
> Quando foi a última vez que você entrou no jogo? Se foi antes de 11.08.2020, você não poderá usá-lo. Você pode usar esta ferramenta para verificar se a API pode encontrar sua conta ou não: https://poe.watch/Account

I'm playing now!

**Comment by chrlsfrmg** [comment] 2022-12-22 09:12
![image](https://user-images.githubusercontent.com/67290803/209099476-9df8bd94-8906-4dc5-a75d-84f9391d0aab.png)

Why are you giving this? I'm playing right now, I've been playing for days now.

**Comment by Omga4000** [comment] 2022-12-22 09:12
@chrlsfrmg 
False positive, I assume. 
Did you ever scan 1.29.1 to see if the result is the same?
You can fully see all of my changes and see I made no significant ones, definitely not something that will trigger a virus alter, unless the original Procurement also triggered it - GitHub doesn't hide anything.

Regarding why this is not working for you, I cannot say.
I gave you this website because the changes I've made are based off of poe-watch's API and if they cannot find you, it won't work.
You'll need to resolve it and have that website recognize you before you can use my changes.

**Comment by chrlsfrmg** [comment] 2022-12-22 09:15
How can I get it recognized? It's saying not found, but I've been playing for several days now.

**Comment by chrlsfrmg** [comment] 2022-12-22 09:15
Help me pls

**Comment by chrlsfrmg** [comment] 2022-12-22 09:16
I play on Steam, is this what is causing this error?

**Comment by Omga4000** [comment] 2022-12-22 09:19
@chrlsfrmg 
Please stop replying in chains. Edit your previous message if you have additional things to mention.

Regarding your issue - I do not know what is causing it.
I don't believe you playing through Steam is the issue as I have tried it with a Steam account and it works.
Contact their support / Discord channel to get it resolved.

**Comment by chrlsfrmg** [comment] 2022-12-22 09:22
> Contact their support / Discord channel to get it resolved.

PoE or Procurement support?

**Comment by Omga4000** [comment] 2022-12-22 09:24
> > Contact their support / Discord channel to get it resolved.
> 
> PoE or Procurement support?

poe-watch, the site I linked. They have a Discord channel listed in their website.

**Comment by chrlsfrmg** [comment] 2022-12-22 09:27
Thank you very much!

**Comment by chrlsfrmg** [comment] 2022-12-22 09:44
I was informed that it is not being shown, as I do not have public stash tabs. The 4 normals that come with the game are not public unless we get 1 paid.

**Comment by Omga4000** [comment] 2022-12-22 20:14
@chrlsfrmg 

Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by chrlsfrmg** [comment] 2022-12-22 20:17
> @chrlsfrmg
> 
> Please try the latest release. It contains a new fix which should work permanently. https://github.com/Omga4000/Procurement/releases/

EXCELLENT!!!! It worked!!!

**Comment by thailyn** [comment] 2022-12-22 21:54
Duplicate of #1140.

**Closed by thailyn** 2022-12-22 21:54 UTC
