### ISSUE TITLE
hollowaycs

### ISSUE THREAD

**Issue by Hollowaycs** [Procurement-PoE/Procurement#1147] opened 2022-12-16 22:37 UTC
im jsut gonna copy and past what was in the DebugInfo folder. please resolve as sonnas u can

[16-12-2022 17:35] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   at POEApi.Model.POEModel.GetAccountName(String realm)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by Omga4000** [comment] 2022-12-22 20:14
Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment] 2022-12-22 21:53
Duplicate of #1140 (as far as I can tell from the info provided).

**Closed by thailyn** 2022-12-22 21:53 UTC
