### ISSUE TITLE
[Error] Cloud flare clearance failed, please wait one minute and try again

### ISSUE THREAD

**Issue by atribe** [Procurement-PoE/Procurement#1128] opened 2020-11-24 22:25 UTC
Saw you fixed this a while ago but it is happening again on 1.29.0

**Comment by DarknessStorm** [comment] 2020-11-25 07:32
yep, confirming.

**Comment by enki001** [comment] 2020-11-25 11:30
yee cloud flare again

**Comment by thailyn** [comment] 2020-11-26 00:53
Thanks for the report, guys.  I can confirm I'm encountering the same issue.  I opened a ticket with the Cloudflare library Procurement uses.  Once that is updated, I'll update Procurement.

**Comment by fireundubh** [comment] 2021-01-03 03:58
> Thanks for the report, guys. I can confirm I'm encountering the same issue. I opened a ticket with the Cloudflare library Procurement uses. Once that is updated, I'll update Procurement.

CloudflareSolverReNgosang is dead and won't be receiving future updates. See: https://github.com/Jackett/Jackett/issues/9029

**Comment by nomis51** [comment] 2021-01-03 21:40
@fireundubh You're totally right, there is no need at all to mess with CloudFlare. I made a issue (#1113) about how to "make it work" again a couple months ago, but the author said it was "sneaky"... which I don't understand why, because I litterally did what every other 3rd party apps for PoE (and other games) are deadling with authentication.

If you want a fast and working app to price you stuff, use [Acquisition](https://github.com/xyzz/acquisition). Haven't been updated for a while, but there's no need, it's just ... workin. It's rock solid.

**Comment by DarknessStorm** [comment] 2021-01-12 07:05
acquisition is not so friendly and comfortable to use... will wait till procurement will be alive again, till that time, unfortunately, trade is lost for me.
And what about tab-trade features: it work only in premium tabs, but they have cost $$$(buying regular stash tabs is much better for your wallet value, so... no.thx)

**Comment by nomis51** [comment] 2021-01-12 19:06
For those who don't like [Acquisition](https://github.com/xyzz/acquisition) and still want to use Procurement (e.g. @DarknessStorm), here's a forked version of Procurement 1.29.0 with a fix for CloudFlare, until it get a proper update from the repository owner.

[Released here](https://github.com/nomis51/Procurement/releases/tag/v1.29.0)

Based on [Procurement Repo](https://github.com/Stickymaddness/Procurement) master branch of today

**Comment by Stickymaddness** [comment] 2021-01-17 13:46
> edit: I'm looking at why you need this in `HttpTransport`, and honestly, I don't really see a good reason. Reviewing how Exile Diary works, you don't need to interact with Cloudflare and shop threads are all but dead now - in favor of in-game store tab features and the official Trade platform. If you dump this dependency and shop thread support, the only drawback is that Procurement users would have to manually move items to store tabs and price them. 🤷‍♂️

The shop thread support is there because many Procurement users rely on it, and don't use premium tabs. Personally, I stopped using the trade functionality in Procurement the second they added the public tab functionality to premium tabs, but for those that can't or won't buy premuim tabs, they turn to Procurement. 


> You're totally right, there is no need at all to mess with CloudFlare. I made a issue (#1113) about how to "make it work" again a couple months ago, but the author said it was "sneaky"... which I don't understand why, because I litterally did what every other 3rd party apps for PoE (and other games) are deadling with authentication.

To clarify, I didn't mean "sneaky" in a negative way, but that you'd got it working in a unintended/clever way. The reason why I closed that PR at the time, is that we updated the Cloudflare library which resolved the issue. During Procurements development we often ran into GGG making changes which broke "creative" ways we got things working, thus I would always favour updating a library over a loophole that GGG might close in the future.

That being said, if the Cloudflare library is dead, and this is the method all 3rd party tools are using, I am open to it.

@thailyn Thoughts? I recall that originally you wanted to submodule a different library, so that we could make changes if need be which I had veto'd in favour of a working library at the time.

I no longer actively develop Procurement, but I do want to get this resolved for everyone.

**Comment by thailyn** [comment] 2021-01-19 01:24
I didn't test out @nomis51 's patch, but I think the intent is good.  Procurement right now is using the POESESSID supplied by the user to do something like log in on the website and get the POESESSID.  This was reasonable when the user provided the user name and password instead, in order to get the POESESSID.  There's no reason anymore to navigate to the login page, and that is the only page protected by Cloudflare.

Ideally, we should use [OAuth2](https://www.reddit.com/r/pathofexiledev/comments/cb9jzy/poe_auth_service/ete1krp/), but that is not publically documented and, last I heard, requires contacting GGG for approval, and would be a sizable effort on our part to support.  However, it would not require the user handing over his credentials to us.

Honestly, I haven't been working on programming stuff for Procurement recently because @Stickymaddness has been a bit distant recently.  I still have a lot of ideas and half-finished projects, though.  I considered forking, but I didn't want to get too far ahead and making things impossible to merge when that does happen (not to mention no one would use the fork).  I also haven't played much PoE for the last league or two, and the two interests feed into each other.

**Comment by Stickymaddness** [comment] 2021-09-11 18:05
@thailyn If you are still interested, I would be happy to hand the reins over to you - I could reference the readme to point to your fork, as well as point [latest-release.txt](https://github.com/Stickymaddness/Procurement/blob/master/latest-release.txt) to your first release, after which I would archive this repo.

**Comment by thailyn** [comment] 2021-09-12 01:23
Hey, @Stickymaddness.  I'm honored you would entrust your project to me.  I am indeed still interested.  However, a suggestion: let's use a Procurement-related GitHub organization, to which we can transfer this repo to.  We can be co-owners of the organization, and you can be as involved after that point as you wish.  In the [transter instruction](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), it says all repos which are a fork of the repo will remain that way after the transfer (preserving everyone else who has forked the repo), and git-related requests will be forwarded to the new repo, as well as all requests for the previous repo location.  I think this means the lookups for latest-release.txt will be redirected, but I'm not positive.  All of the issues and other features will be preserved (aside from Pages, which are not used by Procurement).

I went ahead and created an organization at https://github.com/Procurement-PoE (unfortunately, then name "Procurement" was taken), and invited you to it.  If I understand how permissions work, you will be able to transfer a repo to the organization at that point.  Feel free to message me on the Procurement discord or DM me on discord if you want to go over anything in more details.

**Comment by thailyn** [comment] 2021-09-24 16:26
Hey, @Stickymaddness , what do you think of my suggestion?  It requires a little bit more effort up front, but I think it would allow a smoother transition and open up many more opportunities going forward (additional Procurement-related repos under the same organization, etc.).  Feel free to reach out to me on [discord](https://discord.com/invite/yebkykE) or another method of communication if you want to go over any details somewhere other than a GitHub issue discussion.

**Comment by Stickymaddness** [comment] 2021-10-02 18:15
@thailyn Sorry for the delayed response, but that sounds like a great idea. The invite you sent has expired, if you could send me a new one I'll join and transfer ownership 👍

**Comment by Stickymaddness** [comment] 2021-10-02 18:45
Transfer complete! 🥳

**Closed** 2022-12-22 23:46 UTC
Labels: bug
