### ISSUE TITLE
Error dowloading account name

### ISSUE THREAD

**Issue by DeeDeeDaa** [Procurement-PoE/Procurement#1143] opened 2022-09-11 09:10 UTC
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9542128/DebugInfo.log)

**Comment by Omga4000** [comment] 2022-09-14 20:47
Duplicate: #1140

**Comment by chrlsfrmg** [comment] 2022-12-22 05:37
managed to solve?

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by thailyn** [comment] 2022-12-22 21:51
Duplicate of #1140.

**Closed by thailyn** 2022-12-22 21:51 UTC
