### ISSUE TITLE
Error downloading account name plis

### ISSUE THREAD

**Issue by dequer666** [Procurement-PoE/Procurement#1144] opened 2022-11-07 23:02 UTC
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9956195/DebugInfo.log)

**Comment by chrlsfrmg** [comment] 2022-12-22 05:37
managed to solve?

**Comment by Omga4000** [comment] 2022-12-22 08:58
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by Omga4000** [comment] 2022-12-22 20:13
Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment] 2022-12-22 21:52
Duplicate of #1140.

**Closed by thailyn** 2022-12-22 21:52 UTC
